language: ruby
rvm:
- 2.3
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_798d35b6d3fe_key -iv $encrypted_798d35b6d3fe_iv
  -in .ipfs/maza-web_ipfs-keys.enc -out .ipfs/maza-web_ipfs-keys.tar -d
- tar -xpvf .ipfs/maza-web_ipfs-keys.tar
script: "./script/cibuild.sh"
branches:
  only:
  - develop
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
after_success:
- export CID=$(docker run -d -v ${TRAVIS_BUILD_DIR}/script:/data/script -v $(TRAVIS_BUILD_DIR}:/data/staging -v ${TRAVIS_BUILD_DIR}/.ipfs:/data/ipfs
  ipfs/go-ipfs)
deploy:
- provider: script
  script: bash script/ci-deploy.sh dev $CID
  on:
    branch: develop
- provider: script
  script: bash scripts/ci-deploy.sh prod $CID
  on:
    branch: master
after_deploy:
- docker stop $CID
